### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by Quentinchampenois**
## What ? Why ? 
Add french translation for application strings. I though it could be interesting in the future. 

## Additional context
Let me know if you see missing things about this PR.

### CODE REVIEW

**Comment by p0deje** [comment]
Thank you for the PR! This is great to be merged, but may I ask you to add localization to Preferences window?

**Comment by Quentinchampenois** [comment]
Hi, 

Thank you for your review ! I did not saw the missing translations, I am on it

**Comment by Quentinchampenois** [comment]
I added the missing translations files. Hope it is what you expected.

Let me know if you have further requests

**Comment by p0deje** [comment]
Merged in d628216, thank you!

**Pull request closed without merging**
