### PR TITLE
Add option to position like spotlight search

### PR DESCRIPTION
**Pull request by weisJ**
See #712 

Maybe this could also be consolidated with the `center` option using #826 by adding some "snap" spots for known locations.

Also should I add all other translations as well?

### CODE REVIEW

**Comment by p0deje** [comment]
What do you think if instead of doing this custom positioning, we simply let users position/resize window wherever they want and remember the position? Since the window now hides extra items under a scroll menu, the search bar would be positioned in the same place regardless of the number of items in history.

**Comment by weisJ** [comment]
Yes that is what I proposed in #826 👍🏼

**Comment by p0deje** [comment]
Do you want to replace this PR with a new implementation or create a new one?

**Comment by weisJ** [comment]
Feel free to close it. I'll submit a new one

**Pull request closed without merging**
