### PR TITLE
test Initial translation (arabic-العربية)

### PR DESCRIPTION
**Pull request by columbusux**
pls test i haven't slept for two days...

### CODE REVIEW

**Comment by p0deje** [comment]
> pls test i haven't slept for two days...

Thank you, I'll test. You better get some sleep 😴

**Comment by p0deje** [comment]
Looking through PR, I would ask you to revert the conversion to `Maccy/Localizable.xcstrings`. It's a format that Xcode recommends, but it's not supported by the BartyCrouch tool that is used, so I'm holding off from this migration.

I can undo the change myself with some Vim macros though.

**Comment by p0deje** [comment]
Thank you for the PR, please see my review below!

#### Main window

‏لقطة الشاشة ٢٠٢٤-٠٤-٢٠ في ٠٨ ٣١ ٥١

Everything is translated except for the "Preview" popup. Can you add translations to `Maccy/Menu/Preview/ar.lproj/Preview.strings`?

#### General preferences

‏لقطة الشاشة ٢٠٢٤-٠٤-٢٠ في ٠٨ ٣١ ٥٨

Everything is great with a small exception to the layout of hotkeys controls. I'll fix that myself, you don't have to do anything.

#### Appearance preferences

‏لقطة الشاشة ٢٠٢٤-٠٤-٢٠ في ٠٨ ٤٦ ٢٤

There are some missing translations, can you add them to `Maccy/Settings/ar.lproj/AppearanceSettingsViewController.strings`?


#### Others

The rest looks great, please see some screenshots:

‏لقطة الشاشة ٢٠٢٤-٠٤-٢٠ في ٠٨ ٣٢ ٠٠
‏لقطة الشاشة ٢٠٢٤-٠٤-٢٠ في ٠٨ ٣٢ ١٩
‏لقطة الشاشة ٢٠٢٤-٠٤-٢٠ في ٠٨ ٣٢ ٢٦
‏لقطة الشاشة ٢٠٢٤-٠٤-٢٠ في ٠٨ ٥٢ ٢٨

**Comment by columbusux** [comment]
Thank you for the review, and I apologize. I think I made some mistakes unintentionally. I wasn’t fully focused at the time. Don’t worry, I will do that after I’m free. 🫡
Thanks again brother.

**Comment by MohammedEssehemy** [comment]
Thank you @columbusux for adding the Arabic translation 🙏🏻

**Comment by p0deje** [comment]
Looks great, I'm ready to merge it if you consider it complete.

**Comment by columbusux** [comment]
Yes, you good to go. 
It was an honor for me to help and work with you. I wish you success brother. ♥️

**Comment by p0deje** [comment]
Thank you once again, all the best to you too!

**Pull request merged**
