### PR TITLE
Add option to show application icon

### PR DESCRIPTION
**Pull request by weisJ**
Add option to show app icon in the history list (see #912). The settings toggle is missing translations to languages other than english.
The app icon is also shown in the popover. 

Icons are kept for 24 hours (so they are updated if the application icon changes).

I tried to match the icon size to the visual height of the text next to it (for both the history list and the popover).

image

image

### CODE REVIEW

**Comment by weisJ** [comment]
Changed this to draft as I have a better idea for how to do icon invalidation.

**Comment by weisJ** [comment]
I have changed invalidation to attach a file system event handler to listen for changes to the app file. If it is modified the icon is updated. If it is deleted a fallback icon will be shown and every hours a new attempt at retrieving the icon is made.

**Comment by weisJ** [comment]
Fixed the SwiftLint issues.

Related to this feature: As I have been using it enabled the last two weeks I noticed that due to a lot of copies coming from the web the icons didn't add much context for me in this case. I have now a sort of good working mechanism which shows me the favicon of the webpage the copy originated from instead of the app icon.
Crucially this of course requires making requests to those webpages, which broadens the sandbox requirements for Maccy. Would this feature be something worth while preparing a PR for? (I totally understand if the privacy concerns here outweigh the potential benefits)

**Comment by Romachamp** [comment]
I think just app icons would be enough. Website icons aren’t all that good, and I still use a lot of other apps too. So, everything, which is done currently is pretty good and suits my needs.

**Comment by p0deje** [comment]
Merged in 9f96adc with some smaller changes (refactoring, vertically aligning icon for image copies, extra leading padding).

Thanks again @weisJ, you rock!

**Comment by weisJ** [comment]
Just noticed: If you want the icon to be vertically centred then you could have simply removed the `VStack`. I put it there as I thought having the icon top aligned would look more natural.

**Pull request closed without merging**
