### PR TITLE
Add Norwegian

### PR DESCRIPTION
**Pull request by loseth**
Add Norwegian translation

### CODE REVIEW

**Comment by p0deje** [comment]
Thanks for the pull request! Would you also consider adding translations to preferences files similar to https://github.com/p0deje/Maccy/tree/master/Maccy/Preferences/es.lproj?

**Comment by loseth** [comment]
Sure, I'll get right onto it!

**Comment by loseth** [comment]
Then I think all translations are done and ready to be reviewed.

**Comment by p0deje** [comment]
I had to change XCode project to pick it up correctly (add use NB localization instead of NO) but it's merged in 0cd459f. Thank you!

**Comment by loseth** [comment]
My pleasure, and thank you for the correction.

**Pull request closed without merging**
