### PR TITLE
Enable/disable the search field

### PR DESCRIPTION
**Pull request by inbalboa**
did for myself, but maybe you'll accept :-)

### CODE REVIEW

**Comment by p0deje** [comment]
Thanks for the pull request!

What's the reason for the disabling search field? Is it because you don't like it to be visible or because you want to avoid search functionality at all?

**Comment by inbalboa** [comment]
I think the menu looks prettier without this item. But it's just for my taste :)
It would be cool if the search functionality still worked after hiding the item, but I understand that it is difficult to implement.

**Comment by p0deje** [comment]
I guess all you need to do is set `isVisible` to `false`. That will make it hidden while keeping search functionality.

**Comment by p0deje** [comment]
I've just pushed a different solution that allows to still use search-as-you-type. It's configurable via `hideSearch` setting.

Thank you for the pull request and idea! Even though I haven't merged your changes, I hope you'll like the result.

**Comment by inbalboa** [comment]
Cool, thank you!

**Pull request closed without merging**
