### PR TITLE
ignore events based on `ignoreEvents` pref

### PR DESCRIPTION
**Pull request by thewisenerd**
set this to true before invoking pass, unset at least 2*timerFrequency post copying password, assuming changeCount is updated by then.

### CODE REVIEW

**Comment by p0deje** [comment]
What's the use case of this? I don't quite follow.

**Comment by thewisenerd** [comment]
so, right now, the password copy handling is done as such

```
if let var = pasteboard.items.last {
  copyHooks()
} else {
  removeHooks()
}
```

the else'y bits would be triggered when the password manager would do a `pasteboard.clearContents()`

however, this need not be the case, if the password manager can preemptively tell the clipboard manager that they should start ignoring events, and the password manager co-operates.

since the clipboard data picking happens on `changeCount` *and* `?.last`, `changeCount` will take care of the ignore bits, and the clipboard manager would never read the events which were triggered when the flag was set.

This fits into my workflow of using [passwordstore.org](https://www.passwordstore.org), where there is a platform defined `clip()` function;

it overall looks something like this (for the sake of brevity):
```
clip() {
  before = $(pbpaste)
  defaults write "org.p0deje.Maccy" ignoreEvents true
  ( sleep 5; defaults write "org.p0deje.Maccy" ignoreEvents false ) &
  ( sleep $CLIP_TIME; echo -n "$before" | pbcopy ) &
  echo -n "$1" | pbcopy
}
```

**Comment by thewisenerd** [comment]
the `2*timerFrequency` to await until `ignoreEvents` is unset is so that changeCount is actually reflected

**Comment by p0deje** [comment]
Thank you, merged in 4fe79d8

**Pull request closed without merging**
