### PR TITLE
Improve handling of selected text in the query field

### PR DESCRIPTION
**Pull request by ChaosCoder**
This PR improves the handling of selected text in the query field in the following cases:

- When typing text, the selected query text will be replaced with the new text.
- When hitting the backspace key, the selected query text will be removed.
- When pasting text, the selected query text will be replaced by the new text.

This gives a bit more system feel to the query field.

### CODE REVIEW

**Comment by ChaosCoder** [comment]
Hey @p0deje, is there anything I could do to get this accepted?

**Comment by p0deje** [comment]
@ChaosCoder I'm a bit slow to review now, but I'll look through it within the next couple of weeks.

**Comment by ChaosCoder** [comment]
Sure, take your time! :+1: I just hoped it could be accepted for hacktoberfest, but no worries 🙂

**Comment by p0deje** [comment]
I've tried pulling this to test, but I don't think it behaves correctly. For example, moving the input cursor and pressing delete does nothing. Also, when I select text and then remove it by pressing delete, the selection should be dropped, but it is not.

Could you please test it more thoroughly and address at least these two issues?

**Comment by p0deje** [comment]
Closing since there is no response. Feel free to re-open once the comments are addressed.

**Pull request closed without merging**
