### PR TITLE
Search string visibility

### PR DESCRIPTION
**Pull request by gongchoong**
Created a search string highlight pop up button under the Appearance tap and added italic and underline for extra highlighting options.

Bold: Displays search string in bold font
italic: For better visibility, displays search string in bold and italic font
Underline: For better visibility, displays search string in bold and underlined font

### CODE REVIEW

**Review by p0deje — COMMENTED** [review]
The code looks fine, thank you for submitting it! However, there are a few missing pieces here:

1. There are merge conflicts - I guess too much has changed in master since you started this PR.
2. There is no localization for other languages. I would need this to be able to merge it. Your best way to do so is to install the `bartycrouch` tool, run `bartycrouch update` in Terminal, then unstage changes in files not related to `AppearanceSettingsViewController` and update every localization file to with proper translation. I usually just use Google Translate for that.

**Comment by p0deje** [comment]
@gongchoong Would you still like to finish this PR?

**Comment by gongchoong** [comment]
@p0deje How about I create a new branch from master and cherry-pick the commits?

**Comment by p0deje** [comment]
@gongchoong absolutely, whatever works best for you!

**Comment by gongchoong** [comment]
@p0deje I put up a new PR but the app crashes in AppearanceSettingsViewController when you go Preferences - Appearance. Could you take a look? https://github.com/p0deje/Maccy/pull/728

**Pull request closed without merging**
